name: keyword-releaser

on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dbaldree/keyword-release-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        args: 'FIXED' 